### ISSUE TITLE
StrategicMerge issues

### ISSUE THREAD

**Issue by dfradehubs** [freepik-company/admitik#20]
Hi,

I'm trying to create a ClusterMutationPolicy and I think that strategicmerge is not working well. This is the configuration that i'm using and it is not creating me the initContainer

```
      spec:

        # Resources to be intercepted before reaching the cluster
        interceptedResources:
          - group: "*"
            version: v1
            resource: pods
            operations:
              - CREATE

        # Other resources to be retrieved for conditions templates.
        # They will be included under .sources scope in the template
        sources: []

        # Conditions are optional, so no-conditions means they are always met
        conditions:
          - name: apply-on-specific-mark
            engine: cel
            key: |              
              (has(object.metadata.labels) &&
              object.metadata.labels.exists(label, label == 'admitik.policy.v1/logging')) ||
              
              (has(object.metadata.annotations) &&
              object.metadata.annotations.exists(label, label == 'admitik.policy.v1/logging'))

            value: "true"

        patch:
          type: strategicmerge # JsonPatch | StrategicMerge
          engine: plain+cel
          template: |
            spec:
              initContainers:
              - name: fluent-bit-sidecar
                image: fluent/fluent-bit:4.0.2
                restartPolicy: Always
                imagePullPolicy: IfNotPresent
                command: ["/fluent-bit/bin/fluent-bit"]
                args: ["--config=/fluent-bit/etc/fluentbit.conf"]
                resources:
                  limits:
                    memory: 50Mi
                  requests:
                    cpu: 50m
                    memory: 50Mi
                volumeMounts:
                - name: fluentbit-config
                  mountPath: /fluent-bit/etc/
                  readOnly: true
                - name: k8s-container-logs
                  mountPath: /var/log/containers
                  readOnly: true
                - name: k8s-pods-logs
                  mountPath: /var/log/pods
                  readOnly: true
                - name: fluentbit-pos
                  mountPath: /fluent-bit/pos
                securityContext:
                  runAsNonRoot: true
                  runAsUser: 1000
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
                  readOnlyRootFilesystem: true
              volumes:
              - name: fluentbit-config
                configMap:
                  name: "{{cel: object.metadata.annotations.admitik.policy.v1~1fluentbitConfigmap}}"
              - name: k8s-container-logs
                hostPath:
                  path: /var/log/containers
              - name: k8s-pods-logs
                hostPath:
                  path: /var/log/pods
              - name: fluentbit-pos
                emptyDir: {}
```

Thanks a lot.
